name: Build and Test Back-end Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Récupère le code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Back-end Configuration
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # Utilise OpenJDK Temurin

    # Compile le projet avec Maven
    - name: Build back-end with Maven
      run: mvn -f back/pom.xml clean install

    # Lance les tests
    - name: Run back-end tests
      run: mvn -f back/pom.xml test
