name: Build and Test Full Project (Back-end and Front-end)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Récupère le code source
    - name: Checkout repository
      uses: actions/checkout@v2

    # Back-end Configuration
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build back-end with Maven
      run: mvn -f back/pom.xml clean install

    - name: Run back-end tests
      run: mvn -f back/pom.xml test

    # Front-end Configuration
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Vérifie la version Node.js dans le README

    - name: Install front-end dependencies
      working-directory: ./front
      run: npm install

    - name: Build front-end
      working-directory: ./front
      run: npm run build

    - name: Run front-end tests
      working-directory: ./front
      run: npm test
