name: Build, Test, and Quality Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Back-end Configuration
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and test back-end with Maven
      run: mvn -f back/pom.xml clean verify

    - name: Generate JaCoCo coverage report
      run: mvn -f back/pom.xml jacoco:report

    # Front-end Configuration
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install front-end dependencies
      working-directory: ./front
      run: npm install

    - name: Run front-end tests with coverage
      working-directory: ./front
      run: npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless

    # Archive JaCoCo et Angular reports
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: back/target/site/jacoco/

    - name: Upload Angular coverage report
      uses: actions/upload-artifact@v3
      with:
        name: angular-coverage
        path: front/coverage/

    # Analyse de la qualité du code avec SonarCloud
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      working-directory: ./back  # Change de répertoire vers 'back'
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=nolloV_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
          -Dsonar.organization=nollov \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    # Build et déploiement des images Docker
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push back-end Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-backend:latest -f back/Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-backend:latest

    - name: Build and push front-end Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-frontend:latest -f front/Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-frontend:latest
