name: Quality Analysis

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    # Étape pour récupérer le code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape pour configurer Java 17 (nécessaire pour le back-end)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Étape de compilation et de génération du rapport de couverture pour le back-end
    - name: Build and Generate Coverage Report (Back-end)
      run: mvn -f back/pom.xml clean verify jacoco:report

    # Étape d'analyse SonarCloud pour le Back-end
    - name: SonarCloud Scan (Back-end)
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      working-directory: ./back
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=nolloV_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
          -Dsonar.organization=nollov \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.java.binaries=target/classes

    # Vérification de l'existence du fichier lcov.info pour le Front-end
    - name: Verify Front-end Coverage Report
      working-directory: ./front
      run: |
        if [ ! -f coverage/bobapp/lcov.info ]; then
          echo "Error: Coverage file not found at coverage/bobapp/lcov.info"
          exit 1
        fi

    # Étape d'analyse SonarCloud pour le Front-end
    - name: SonarCloud Scan (Front-end)
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      working-directory: ./front
      run: |
        npx sonar-scanner \
          -Dsonar.projectKey=nolloV_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
          -Dsonar.organization=nollov \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sources=src \
          -Dsonar.tests=src \
          -Dsonar.typescript.lcov.reportPaths=coverage/bobapp/lcov.info
