name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build and test back-end with Maven
      run: mvn -f back/pom.xml clean verify

    - name: Generate JaCoCo coverage report
      run: mvn -f back/pom.xml jacoco:report

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install front-end dependencies
      working-directory: ./front
      run: npm install

    - name: Run front-end tests with coverage
      working-directory: ./front
      run: npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: back/target/site/jacoco/

    - name: Upload Angular coverage report
      uses: actions/upload-artifact@v3
      with:
        name: angular-coverage
        path: front/coverage/
